global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Hotel Booking Backend
  - job_name: 'hotel-booking-backend'
    static_configs:
      - targets: ['hotel-booking-website-backend-1:7000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node Exporter for system metrics (commented out as not deployed)
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # cAdvisor for container metrics (commented out as not deployed)
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']

  # MongoDB metrics (commented out as not deployed)
  # - job_name: 'mongodb'
  #   static_configs:
  #     - targets: ['mongodb-exporter:9216']
  #   scrape_interval: 30s 