apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: hotel-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/hotel-booking-website/backend:latest
        ports:
        - containerPort: 7000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: hotel-booking-config
              key: NODE_ENV
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: hotel-booking-secrets
              key: jwt-secret
        - name: MONGODB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: hotel-booking-secrets
              key: mongodb-connection-string
        livenessProbe:
          httpGet:
            path: /health
            port: 7000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: hotel-booking
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 7000
  type: ClusterIP 