# This is a template file - actual secrets should be created securely
# kubectl create secret generic hotel-booking-secrets --from-literal=jwt-secret=your-jwt-secret --namespace=hotel-booking

apiVersion: v1
kind: Secret
metadata:
  name: hotel-booking-secrets
  namespace: hotel-booking
  labels:
    app: vacays
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  jwt-secret: <base64-encoded-jwt-secret>
  mongodb-connection-string: <base64-encoded-mongodb-connection>
  cloudinary-cloud-name: <base64-encoded-cloudinary-cloud-name>
  cloudinary-api-key: <base64-encoded-cloudinary-api-key>
  cloudinary-api-secret: <base64-encoded-cloudinary-api-secret>
  stripe-api-key: <base64-encoded-stripe-api-key>
  stripe-pub-key: <base64-encoded-stripe-pub-key>
  mongo-root-username: <base64-encoded-mongo-username>
  mongo-root-password: <base64-encoded-mongo-password> 